# Generated by Django 6.0.4 on 2026-05-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviata', 'Inviata'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], default='bozza', max_length=20)),
                ('note_direttore', models.TextField(blank=True)),
                ('cig', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste', to='selco.fornitore')),
            ],
            options={
                'verbose_name': 'Richiesta',
                'verbose_name_plural': 'Richieste',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='allegati/')),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='selco.richiesta')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
                'ordering': ['caricato_il'],
            },
        ),
    ]
