# Generated by Django 6.0.4 on 2026-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='certificazione',
            field=models.FileField(blank=True, null=True, upload_to='fornitori/'),
        ),
    ]
